### ISSUE TITLE
dc_loss_v1 loss issue

### ISSUE THREAD

**Issue by hjfdsssdg** [gaobb/DCFS#2]
Hi author, I would like to learn more about your thesis work，when I train with dc_loss_v1, the loss changes to NAN quickly, while the trial version of dc_loss does not. 
For example:
**'FloatingPointError: Loss became infinite or NaN at iteration=32!
loss_dict = {'loss_cls': nan, 'loss_box_reg': nan, 'loss_rpn_cls': 0.6878441572189331, 'loss_rpn_loc': 0.002770405262708664}'**

Do you know what's wrong with the code? ThanKs!

**Comment by gaobb** [comment]
Hi， 

Thank you very much for your attention to our work.  I suggest that you use "dc_loss" instead of "dc_loss_v1".  The implementation functions of "dc_loss" and "dc_loss_v1" are exactly the same, but the code of the dc_loss is more concise. 

In my case, I don't meet the NAN issues when I use the "dc_loss_v1".
