### ISSUE TITLE
Could you publish the trained weights?

### ISSUE THREAD

**Issue by stweigand97** [gaobb/DCFS#4]
Could you publish the weights, so that its easiert to reproduce your findings?

**Comment by gaobb** [comment]
Thanks for your interest in our work.

We are unable to publicly release the pre-trained FSOD/gFSOD models due to their substantial storage requirements. For instance, the FSOD model consists of 6 different shots (1, 2, 3, 5, 10, 30), and each shot is associated with 10 seeds, resulting in a total of 60 models for a single FSOD method.

Nonetheless, you should be able to replicate our results using the provided code. Additionally, please feel free to reach out if you have any questions or need further discussion.
